/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */
declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import '@stencil/router';
import 'ionicons';
import '@ionic/core';
import '@stencil/redux';

import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';
import {
  IExchange,
} from './model';

import {
  AppHeaderToolbar as AppHeaderToolbar
} from './components/app-header-toolbar/app-header-toolbar';

declare global {
  interface HTMLAppHeaderToolbarElement extends AppHeaderToolbar, HTMLStencilElement {
  }
  var HTMLAppHeaderToolbarElement: {
    prototype: HTMLAppHeaderToolbarElement;
    new (): HTMLAppHeaderToolbarElement;
  };
  interface HTMLElementTagNameMap {
    "app-header-toolbar": HTMLAppHeaderToolbarElement;
  }
  interface ElementTagNameMap {
    "app-header-toolbar": HTMLAppHeaderToolbarElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "app-header-toolbar": JSXElements.AppHeaderToolbarAttributes;
    }
  }
  namespace JSXElements {
    export interface AppHeaderToolbarAttributes extends HTMLAttributes {
      buttons?: JSX.Element[];
      history?: RouterHistory;
      title?: string;
    }
  }
}


import {
  AppHeader as AppHeader
} from './components/app-header/app-header';

declare global {
  interface HTMLAppHeaderElement extends AppHeader, HTMLStencilElement {
  }
  var HTMLAppHeaderElement: {
    prototype: HTMLAppHeaderElement;
    new (): HTMLAppHeaderElement;
  };
  interface HTMLElementTagNameMap {
    "app-header": HTMLAppHeaderElement;
  }
  interface ElementTagNameMap {
    "app-header": HTMLAppHeaderElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "app-header": JSXElements.AppHeaderAttributes;
    }
  }
  namespace JSXElements {
    export interface AppHeaderAttributes extends HTMLAttributes {
      title?: string;
    }
  }
}


import {
  AppHome as AppHome
} from './components/app-home/app-home';

declare global {
  interface HTMLAppHomeElement extends AppHome, HTMLStencilElement {
  }
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };
  interface HTMLElementTagNameMap {
    "app-home": HTMLAppHomeElement;
  }
  interface ElementTagNameMap {
    "app-home": HTMLAppHomeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "app-home": JSXElements.AppHomeAttributes;
    }
  }
  namespace JSXElements {
    export interface AppHomeAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  AppMainMenuButton as AppMainMenuButton
} from './components/app-main-menu-button/app-main-menu-button';

declare global {
  interface HTMLAppMainMenuButtonElement extends AppMainMenuButton, HTMLStencilElement {
  }
  var HTMLAppMainMenuButtonElement: {
    prototype: HTMLAppMainMenuButtonElement;
    new (): HTMLAppMainMenuButtonElement;
  };
  interface HTMLElementTagNameMap {
    "app-main-menu-button": HTMLAppMainMenuButtonElement;
  }
  interface ElementTagNameMap {
    "app-main-menu-button": HTMLAppMainMenuButtonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "app-main-menu-button": JSXElements.AppMainMenuButtonAttributes;
    }
  }
  namespace JSXElements {
    export interface AppMainMenuButtonAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  AppProfile as AppProfile
} from './components/app-profile/app-profile';

declare global {
  interface HTMLAppProfileElement extends AppProfile, HTMLStencilElement {
  }
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };
  interface HTMLElementTagNameMap {
    "app-profile": HTMLAppProfileElement;
  }
  interface ElementTagNameMap {
    "app-profile": HTMLAppProfileElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "app-profile": JSXElements.AppProfileAttributes;
    }
  }
  namespace JSXElements {
    export interface AppProfileAttributes extends HTMLAttributes {
      history?: RouterHistory;
      match?: MatchResults;
    }
  }
}


import {
  AppTest as AppTest
} from './components/app-test/app-test';

declare global {
  interface HTMLAppTestElement extends AppTest, HTMLStencilElement {
  }
  var HTMLAppTestElement: {
    prototype: HTMLAppTestElement;
    new (): HTMLAppTestElement;
  };
  interface HTMLElementTagNameMap {
    "app-test": HTMLAppTestElement;
  }
  interface ElementTagNameMap {
    "app-test": HTMLAppTestElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "app-test": JSXElements.AppTestAttributes;
    }
  }
  namespace JSXElements {
    export interface AppTestAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  CryptobuddyApp as CryptobuddyApp
} from './components/cryptobuddy-app/cryptobuddy-app';

declare global {
  interface HTMLCryptobuddyAppElement extends CryptobuddyApp, HTMLStencilElement {
  }
  var HTMLCryptobuddyAppElement: {
    prototype: HTMLCryptobuddyAppElement;
    new (): HTMLCryptobuddyAppElement;
  };
  interface HTMLElementTagNameMap {
    "cryptobuddy-app": HTMLCryptobuddyAppElement;
  }
  interface ElementTagNameMap {
    "cryptobuddy-app": HTMLCryptobuddyAppElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "cryptobuddy-app": JSXElements.CryptobuddyAppAttributes;
    }
  }
  namespace JSXElements {
    export interface CryptobuddyAppAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  ExchangeItem as ExchangeItem
} from './components/exchange-item/exchange-item';

declare global {
  interface HTMLExchangeItemElement extends ExchangeItem, HTMLStencilElement {
  }
  var HTMLExchangeItemElement: {
    prototype: HTMLExchangeItemElement;
    new (): HTMLExchangeItemElement;
  };
  interface HTMLElementTagNameMap {
    "exchange-item": HTMLExchangeItemElement;
  }
  interface ElementTagNameMap {
    "exchange-item": HTMLExchangeItemElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "exchange-item": JSXElements.ExchangeItemAttributes;
    }
  }
  namespace JSXElements {
    export interface ExchangeItemAttributes extends HTMLAttributes {
      exchange?: IExchange;
    }
  }
}


import {
  ExchangesList as ExchangesList
} from './components/exchanges-list/exchanges-list';

declare global {
  interface HTMLExchangesListElement extends ExchangesList, HTMLStencilElement {
  }
  var HTMLExchangesListElement: {
    prototype: HTMLExchangesListElement;
    new (): HTMLExchangesListElement;
  };
  interface HTMLElementTagNameMap {
    "exchanges-list": HTMLExchangesListElement;
  }
  interface ElementTagNameMap {
    "exchanges-list": HTMLExchangesListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "exchanges-list": JSXElements.ExchangesListAttributes;
    }
  }
  namespace JSXElements {
    export interface ExchangesListAttributes extends HTMLAttributes {
      history?: RouterHistory;
      match?: MatchResults;
    }
  }
}


import {
  LazyImg as LazyImg
} from './components/lazy-img/lazy-img';

declare global {
  interface HTMLLazyImgElement extends LazyImg, HTMLStencilElement {
  }
  var HTMLLazyImgElement: {
    prototype: HTMLLazyImgElement;
    new (): HTMLLazyImgElement;
  };
  interface HTMLElementTagNameMap {
    "lazy-img": HTMLLazyImgElement;
  }
  interface ElementTagNameMap {
    "lazy-img": HTMLLazyImgElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "lazy-img": JSXElements.LazyImgAttributes;
    }
  }
  namespace JSXElements {
    export interface LazyImgAttributes extends HTMLAttributes {
      alt?: string;
      src?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
